modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Respawning%20Shulkers"
logoFile="icon.png"

[[mods]]
modId="respawningshulkers"
version="3.7"
displayName="Respawning Shulkers"
displayURL="https://serilum.com/mod/respawning-shulkers"
authors="Rick South"
description='''Shulkers will respawn on their death location after a configurable delay to make them more sustainable.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.respawningshulkers]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.respawningshulkers]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"